import { uniqueId } from 'lodash';

import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconShoppingCart,
  IconAperture,
  IconLayout,
  IconSettings,
  IconHelp,
  IconZoomCode,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBorderStyle2,
  IconAppWindow,
  IconNotebook,
  IconFileCheck,
  IconChartHistogram,
  IconChartPie2,
  IconChartScatter,
  IconChartPpf,
  IconChartArcs3,
  IconChartPie,
  IconListTree,
  IconWallet,
  IconSchool,
  IconTimeline,
  IconMap,
  IconListCheck,
  IconCalendarTime,
  IconHistory,
} from '@tabler/icons-react';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Main Navigation',
  },
  {
    id: uniqueId(),
    title: 'Analytical',
    icon: IconChartPie,
    href: '/analytical',
    permission: ['landlord.dashboard'],
  },
  {
    id: uniqueId(),
    title: 'ACL Manager',
    icon: IconSettings,
    href: '/acl_manager',
    // permission: ['landlord.acl.index'],
  },
  {
    id: uniqueId(),
    title: 'Calendar',
    icon: IconCalendarTime,
    href: '/calendar',
    permission: ['landlord.calendar.index'],
  },
  {
    id: uniqueId(),
    title: 'Agent',
    icon: IconUserCircle,
    href: '/agent',
    permission: ['landlord.organization.index'],
  },
  {
    id: uniqueId(),
    title: 'Activity Log',
    icon: IconHistory,
    href: '/activity-log',
    permission: ['landlord.activity_log.index'],
  },
  {
    id: uniqueId(),
    title: 'School',
    icon: IconSchool,
    href: '/school',
    permission: ['landlord.school.index'],
  },
  {
    id: uniqueId(),
    title: 'EduTier',
    icon: IconListTree,
    href: '/plan',
    permission: ['landlord.plan.index'],
  },
  {
    id: uniqueId(),
    title: 'Gateway',
    icon: IconWallet,
    href: '/gateway',
  },
  {
    id: uniqueId(),
    title: 'Chat',
    icon: IconMessage2,
    href: '/chat',
  },
  {
    id: uniqueId(),
    title: 'Mail',
    icon: IconMail,
    href: '/mail',
  },
  {
    id: uniqueId(),
    title: 'PHET Stimulation',
    icon: IconAppWindow,
    children: [
      {
        id: uniqueId(),
        title: 'Subject & Topics',
        icon: IconPoint,
        href: '/phet/subject_topics',
      },
      {
        id: uniqueId(),
        title: 'Stimulation Links',
        icon: IconPoint,
        href: '/phet/stimulation_links',
      },
    ],
  },

  {
    id: uniqueId(),
    title: 'Tenant Subscriptions',
    icon: IconAppWindow,
    href: '/agent/subscriptions',
    permission: ['landlord.subscription.index'],
  },

];

export default Menuitems;
